### ISSUE TITLE
Invalid opcode 153/1/8 on Silex

### ISSUE THREAD

**Issue by jgmullor** [eaccelerator/eaccelerator#16]
Hello!

I've started using eAccelerator, with nginx+php-fpm, but i'm getting lots of erros with "Invalid opcode", the most common one is this:

Invalid opcode 153/1/8. in /var/www/x/vendor/silex/silex/src/Silex/Application.php on line 64

And in line 64 I've got his:

this['autoloader'] = function () {
            throw new \RuntimeException('You tried to access the autoloader service. The autoloader has been removed from Silex. It is recommended that you use Composer to manage your dependencies and handle your autoloading. See http://getcomposer.org for more information.');
        };

Any one knows where's the problem?
Thanks!! :)

**Comment by bennylin** [comment]
Hi, I installed MediaWiki 1.25 and I got this error too.

 Fatal error: Invalid opcode 153/1/8. in /w/includes/registration/ExtensionRegistry.php on line 247

Is there no patch on this bug yet?

**Comment by katmai** [comment]
eaccelerator has not been maintained for ages. use the neweracracker fork. all fixes went in it.

**Comment by bennylin** [comment]
Thanks.
