### ISSUE TITLE
Project dead?

### ISSUE THREAD

**Issue by riotera** [eaccelerator/eaccelerator#35]
I don't know but there are other solutions:

https://github.com/zendtech/ZendOptimizerPlus

**Comment by NewEraCracker** [comment]
I think it is time for we to move to a fork. I am maintain an eAccelerator that works from PHP 5.1 to PHP 5.5 and from my limited testing did not had problems with crashes.

Today I have cherry-picked some stuff from other forks and done some extensive changes to some pieces of code.

If anyone still wants to use it I'd recommend moving to my fork:
https://github.com/NewEraCracker/eaccelerator

This project will still live as it is humanly possible.

Regards,
NewEraCracker

**Comment by katmai** [comment]
im on watch for your fork
