### ISSUE TITLE
fatal error: 'php_logos.h' file not found

### ISSUE THREAD

**Issue by baksosapi** [eaccelerator/eaccelerator#54]
I have problem with php_logos.h
Step 1.

```
ian-mbp:eaccelerator-0.9.6.1 wildan$ $PHP_PREFIX/bin/phpize
Configuring for:
PHP Api Version:         20131106
Zend Module Api No:      20131226
Zend Extension Api No:   220131226
```

Step 2

```
ian-mbp:eaccelerator-0.9.6.1 wildan$ ./configure --enable-shared --with-php-config=$PHP_PREFIX/bin/php-config
```

Step 3. failed

```
ian-mbp:eaccelerator-0.9.6.1 wildan$ make
```

and the result is

```
...
/Users/wildan/Downloads/eaccelerator-0.9.6.1/eaccelerator.c:66:10: fatal error: 'php_logos.h' file not found
#include "php_logos.h"
         ^
1 error generated.
make: *** [eaccelerator.lo] Error 1
```

**Comment by NewEraCracker** [comment]
If you're on PHP 5.5 you should use my fork of eAccelerator:
https://github.com/NewEraCracker/eaccelerator

Otherwise switch to another OPcode caching solution.

**Comment by katmai** [comment]
yeah newera is a boss. that fork works just fine.

**Comment by ioaniatr** [comment]
I followed installation instractions, but in my code
` if (!is_callable('eaccelerator_encode') && !extension_loaded('eaccelerator.so')) { 
//true
}`

What am i doing wrong?

**Comment by NewEraCracker** [comment]
encoder is no longer available.

**Comment by coolblueray** [comment]
I have faced similar problems with PHP 5.6.30. Following Steps are used:
1.  I used this version https://github.com/NewEraCracker/eaccelerator.
2.  In order to fix, I had to replace IS_CONSTANT_ARRAY with IS_CONSTANT_AST in ea_restore.c and ea_store.c files. 

it is working.
